spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dvd_store
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: public
      connection-timeout: 20000
      minimum-idle: 2
  data:
    redis:
      host: localhost
      port: 6379
      jedis:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 2
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: postgres
    password: postgres
    baseline-description: "init"
    baseline-version: 0
    locations: classpath:db/migration
