apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-claim
spec:
  volumeName: psql-pv
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi