apiVersion: v1
kind: PersistentVolume
metadata:
    name: psql-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: standard
  hostPath:
    path: /data
    type: DirectoryOrCreate


